// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package go_micro_srv_hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义 Hello 接口请求
type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ids                  []int64  `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Job                  *Job     `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	User                 *User    `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *Request) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Request) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Request) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Request2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request2) Reset()         { *m = Request2{} }
func (m *Request2) String() string { return proto.CompactTextString(m) }
func (*Request2) ProtoMessage()    {}
func (*Request2) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *Request2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request2.Unmarshal(m, b)
}
func (m *Request2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request2.Marshal(b, m, deterministic)
}
func (m *Request2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request2.Merge(m, src)
}
func (m *Request2) XXX_Size() int {
	return xxx_messageInfo_Request2.Size(m)
}
func (m *Request2) XXX_DiscardUnknown() {
	xxx_messageInfo_Request2.DiscardUnknown(m)
}

var xxx_messageInfo_Request2 proto.InternalMessageInfo

func (m *Request2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request2) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type User struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	//    Job job = 3 ;
	Jobs                 []*Job   `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *User) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Salary               float64  `protobuf:"fixed64,2,opt,name=salary,proto3" json:"salary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetSalary() float64 {
	if m != nil {
		return m.Salary
	}
	return 0
}

// 定义 Hello 接口响应
type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.hello.Request")
	proto.RegisterType((*Request2)(nil), "go.micro.srv.hello.Request2")
	proto.RegisterType((*User)(nil), "go.micro.srv.hello.User")
	proto.RegisterType((*Job)(nil), "go.micro.srv.hello.Job")
	proto.RegisterType((*Response)(nil), "go.micro.srv.hello.Response")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0xaf, 0x6b, 0xa7, 0x97, 0x9e, 0x2e, 0xe8, 0x0c, 0x60, 0x41, 0x87, 0xc8, 0x53, 0x10,
	0xc8, 0x82, 0xf0, 0x0a, 0x08, 0xa1, 0x8e, 0x46, 0x4c, 0x4c, 0x0e, 0xb1, 0x42, 0xab, 0xa4, 0x2e,
	0x76, 0x8b, 0xd4, 0xe7, 0xe0, 0x65, 0x78, 0x3c, 0xe4, 0xd3, 0x6c, 0xa4, 0x65, 0xca, 0x1f, 0x9d,
	0x2f, 0x5f, 0xfe, 0x63, 0x19, 0xa6, 0xef, 0xae, 0x6d, 0xbd, 0x5e, 0x07, 0xbf, 0xf1, 0x88, 0x8d,
	0xd7, 0xdd, 0xe2, 0x2d, 0x78, 0x1d, 0xc3, 0xa7, 0xa6, 0x89, 0xfa, 0x66, 0xf0, 0xdf, 0xb8, 0x8f,
	0xad, 0x8b, 0x1b, 0x44, 0x10, 0x2b, 0xdb, 0x39, 0xc9, 0x72, 0x56, 0x4c, 0x0c, 0x65, 0x3c, 0x05,
	0xbe, 0xa8, 0xa3, 0x1c, 0xe5, 0xbc, 0xe0, 0x26, 0x45, 0xbc, 0x02, 0xbe, 0xf4, 0x95, 0xe4, 0x39,
	0x2b, 0xa6, 0xe5, 0xb9, 0xfe, 0xed, 0xd4, 0x73, 0x5f, 0x99, 0xc4, 0xe0, 0x0d, 0x88, 0x6d, 0x74,
	0x41, 0x0a, 0x62, 0xe5, 0x10, 0xfb, 0x12, 0x5d, 0x30, 0x44, 0xa1, 0x86, 0x2c, 0x3d, 0xa3, 0xcc,
	0x72, 0x7e, 0x14, 0xdf, 0x63, 0xea, 0x16, 0x4e, 0xfa, 0xe6, 0xe5, 0xa1, 0xea, 0xb6, 0x71, 0x72,
	0x94, 0xb3, 0x22, 0x33, 0x29, 0xaa, 0x57, 0x10, 0x49, 0x30, 0x48, 0x23, 0x08, 0x5b, 0xd7, 0x81,
	0xf0, 0x89, 0xa1, 0x8c, 0xd7, 0x20, 0x96, 0xbe, 0x8a, 0x92, 0x53, 0xa1, 0x83, 0xbb, 0x12, 0xa4,
	0xee, 0x80, 0xcf, 0x7d, 0x35, 0xe8, 0x3e, 0x83, 0x71, 0xb4, 0xad, 0x0d, 0x3b, 0xb2, 0x33, 0xd3,
	0xbf, 0xa9, 0x59, 0xda, 0x20, 0xae, 0xfd, 0x2a, 0x52, 0xdb, 0x2e, 0x36, 0xfd, 0x67, 0x29, 0x96,
	0x5f, 0x0c, 0xf8, 0xb3, 0xdd, 0xe1, 0x03, 0x64, 0x4f, 0xe9, 0x5f, 0x78, 0x39, 0x54, 0xa0, 0x3f,
	0x82, 0x8b, 0xd9, 0xf0, 0x70, 0x6f, 0x57, 0xff, 0xf0, 0x11, 0xc6, 0x64, 0x29, 0x71, 0x76, 0x44,
	0x53, 0xfe, 0xe5, 0xa9, 0xc6, 0x74, 0x97, 0xee, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0xf5,
	0x8c, 0x55, 0x5a, 0x02, 0x00, 0x00,
}
